/* Generated By:JavaCC: Do not edit this line. MedParserTokenManager.java */
package med;
import java.io.*;

/** Token Manager. */
public class MedParserTokenManager implements MedParserConstants
{

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0)
{
   switch (pos)
   {
      case 0:
         if ((active0 & 0x2000000L) != 0L)
            return 56;
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 44:
         return jjStopAtPos(0, 10);
      case 80:
         return jjMoveStringLiteralDfa1_0(0x2000000L);
      case 123:
         return jjStopAtPos(0, 8);
      case 125:
         return jjStopAtPos(0, 9);
      default :
         return jjMoveNfa_0(7, 0);
   }
}
private int jjMoveStringLiteralDfa1_0(long active0)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0);
      return 1;
   }
   switch(curChar)
   {
      case 72:
         return jjMoveStringLiteralDfa2_0(active0, 0x2000000L);
      default :
         break;
   }
   return jjStartNfa_0(0, active0);
}
private int jjMoveStringLiteralDfa2_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(0, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0);
      return 2;
   }
   switch(curChar)
   {
      case 79:
         return jjMoveStringLiteralDfa3_0(active0, 0x2000000L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0);
}
private int jjMoveStringLiteralDfa3_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(1, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0);
      return 3;
   }
   switch(curChar)
   {
      case 78:
         return jjMoveStringLiteralDfa4_0(active0, 0x2000000L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0);
}
private int jjMoveStringLiteralDfa4_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(2, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0);
      return 4;
   }
   switch(curChar)
   {
      case 69:
         return jjMoveStringLiteralDfa5_0(active0, 0x2000000L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0);
}
private int jjMoveStringLiteralDfa5_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(3, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0);
      return 5;
   }
   switch(curChar)
   {
      case 83:
         if ((active0 & 0x2000000L) != 0L)
            return jjStopAtPos(5, 25);
         break;
      default :
         break;
   }
   return jjStartNfa_0(4, active0);
}
private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 280;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 7:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 12)
                        kind = 12;
                     jjstateSet[jjnewStateCnt++] = 155;
                  }
                  else if (curChar == 34)
                     jjCheckNAdd(31);
                  break;
               case 30:
                  if (curChar == 34)
                     jjCheckNAdd(31);
                  break;
               case 31:
                  if (curChar == 32)
                     jjCheckNAddTwoStates(31, 32);
                  break;
               case 32:
                  if (curChar == 34 && kind > 19)
                     kind = 19;
                  break;
               case 34:
                  if (curChar == 58)
                     jjCheckNAddStates(0, 2);
                  break;
               case 35:
                  if ((0x100003600L & l) != 0L)
                     jjCheckNAddStates(0, 2);
                  break;
               case 36:
                  if (curChar == 43)
                     jjCheckNAdd(37);
                  break;
               case 37:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 26)
                     kind = 26;
                  jjCheckNAddStates(3, 5);
                  break;
               case 38:
                  if ((0x100003600L & l) != 0L)
                     jjCheckNAddTwoStates(38, 43);
                  break;
               case 40:
                  if ((0x100003600L & l) != 0L)
                     jjCheckNAddTwoStates(40, 41);
                  break;
               case 41:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 26)
                     kind = 26;
                  jjCheckNAdd(41);
                  break;
               case 48:
                  if ((0x100003600L & l) != 0L)
                     jjAddStates(6, 7);
                  break;
               case 49:
                  if (curChar == 34)
                     jjCheckNAdd(50);
                  break;
               case 50:
                  if (curChar == 32)
                     jjCheckNAddTwoStates(50, 51);
                  break;
               case 51:
                  if (curChar == 34 && kind > 30)
                     kind = 30;
                  break;
               case 59:
                  if ((0x100003600L & l) != 0L)
                     jjAddStates(8, 9);
                  break;
               case 62:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 63;
                  break;
               case 63:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 64;
                  break;
               case 64:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 65;
                  break;
               case 65:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 66;
                  break;
               case 66:
                  if ((0x3ff000000000000L & l) != 0L && kind > 31)
                     kind = 31;
                  break;
               case 81:
                  if ((0x100003600L & l) != 0L)
                     jjAddStates(10, 11);
                  break;
               case 82:
                  if (curChar == 34)
                     jjCheckNAdd(83);
                  break;
               case 83:
                  if (curChar == 32)
                     jjCheckNAddTwoStates(83, 84);
                  break;
               case 84:
                  if (curChar == 34 && kind > 6)
                     kind = 6;
                  break;
               case 104:
                  if ((0x100003600L & l) != 0L)
                     jjAddStates(12, 17);
                  break;
               case 106:
                  if (curChar == 44)
                     jjAddStates(18, 22);
                  break;
               case 110:
                  if (curChar == 40)
                     jjstateSet[jjnewStateCnt++] = 111;
                  break;
               case 111:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 112;
                  break;
               case 112:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 113;
                  break;
               case 113:
                  if (curChar == 58)
                     jjstateSet[jjnewStateCnt++] = 114;
                  break;
               case 114:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 115;
                  break;
               case 115:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 116;
                  break;
               case 116:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 117;
                  break;
               case 117:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 118;
                  break;
               case 118:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 119;
                  break;
               case 119:
                  if (curChar == 58)
                     jjstateSet[jjnewStateCnt++] = 120;
                  break;
               case 120:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 121;
                  break;
               case 121:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 122;
                  break;
               case 122:
                  if (curChar == 41)
                     kind = 7;
                  break;
               case 154:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 12)
                     kind = 12;
                  jjstateSet[jjnewStateCnt++] = 155;
                  break;
               case 155:
                  if ((0x3ff000000000000L & l) != 0L && kind > 13)
                     kind = 13;
                  break;
               case 164:
                  if ((0x100003600L & l) != 0L)
                     jjAddStates(23, 24);
                  break;
               case 165:
                  if (curChar == 34)
                     jjCheckNAdd(166);
                  break;
               case 166:
                  if (curChar == 32)
                     jjCheckNAddTwoStates(166, 167);
                  break;
               case 167:
                  if (curChar == 34)
                     jjCheckNAddTwoStates(168, 180);
                  break;
               case 168:
                  if ((0x100003600L & l) != 0L)
                     jjCheckNAddTwoStates(168, 180);
                  break;
               case 170:
                  if (curChar == 32)
                     jjstateSet[jjnewStateCnt++] = 171;
                  break;
               case 171:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 172;
                  break;
               case 172:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 173;
                  break;
               case 173:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 174;
                  break;
               case 174:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 175;
                  break;
               case 175:
                  if ((0x3ff000000000000L & l) != 0L && kind > 21)
                     kind = 21;
                  break;
               case 186:
                  if ((0x100003600L & l) != 0L)
                     jjAddStates(25, 26);
                  break;
               case 187:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(27, 36);
                  break;
               case 188:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(37, 45);
                  break;
               case 189:
                  if ((0x100003600L & l) != 0L)
                     jjCheckNAddStates(37, 45);
                  break;
               case 191:
                  if ((0x100003600L & l) != 0L)
                     jjAddStates(46, 47);
                  break;
               case 192:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 193;
                  break;
               case 193:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 194;
                  break;
               case 194:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 195;
                  break;
               case 195:
                  if ((0x3ff000000000000L & l) != 0L && kind > 33)
                     kind = 33;
                  break;
               case 271:
                  if ((0x100003600L & l) != 0L)
                     jjAddStates(48, 49);
                  break;
               case 272:
                  if (curChar == 34)
                     jjCheckNAdd(273);
                  break;
               case 273:
                  if ((0x3ffb00100000000L & l) != 0L)
                     jjCheckNAddTwoStates(273, 274);
                  break;
               case 274:
                  if (curChar == 34 && kind > 35)
                     kind = 35;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 7:
                  if (curChar == 65)
                     jjAddStates(50, 52);
                  else if (curChar == 68)
                     jjAddStates(53, 55);
                  else if (curChar == 72)
                     jjAddStates(56, 57);
                  else if (curChar == 77)
                     jjAddStates(58, 61);
                  else if (curChar == 74)
                     jjAddStates(62, 64);
                  else if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 58;
                  else if (curChar == 80)
                     jjstateSet[jjnewStateCnt++] = 56;
                  else if (curChar == 87)
                     jjstateSet[jjnewStateCnt++] = 45;
                  else if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 28;
                  else if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 21;
                  else if (curChar == 83)
                     jjstateSet[jjnewStateCnt++] = 15;
                  else if (curChar == 70)
                     jjstateSet[jjnewStateCnt++] = 6;
                  break;
               case 0:
                  if (curChar == 121 && kind > 16)
                     kind = 16;
                  break;
               case 1:
               case 69:
                  if (curChar == 114)
                     jjCheckNAdd(0);
                  break;
               case 2:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 3:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 2;
                  break;
               case 4:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 3;
                  break;
               case 5:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 4;
                  break;
               case 6:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 5;
                  break;
               case 8:
                  if (curChar == 114 && kind > 16)
                     kind = 16;
                  break;
               case 9:
               case 17:
               case 23:
               case 157:
                  if (curChar == 101)
                     jjCheckNAdd(8);
                  break;
               case 10:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 9;
                  break;
               case 11:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 10;
                  break;
               case 12:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 11;
                  break;
               case 13:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 12;
                  break;
               case 14:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 13;
                  break;
               case 15:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 14;
                  break;
               case 16:
                  if (curChar == 83)
                     jjstateSet[jjnewStateCnt++] = 15;
                  break;
               case 18:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 17;
                  break;
               case 19:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 18;
                  break;
               case 20:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 19;
                  break;
               case 21:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 20;
                  break;
               case 22:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 21;
                  break;
               case 24:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 23;
                  break;
               case 25:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 24;
                  break;
               case 26:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 25;
                  break;
               case 27:
                  if (curChar == 118)
                     jjstateSet[jjnewStateCnt++] = 26;
                  break;
               case 28:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 27;
                  break;
               case 29:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 28;
                  break;
               case 31:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjAddStates(65, 66);
                  break;
               case 33:
                  if (curChar == 75)
                     jjCheckNAdd(34);
                  break;
               case 39:
                  if (curChar == 84)
                     jjAddStates(67, 68);
                  break;
               case 42:
                  if (curChar == 88)
                     jjstateSet[jjnewStateCnt++] = 39;
                  break;
               case 43:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 42;
                  break;
               case 44:
                  if (curChar == 82)
                     jjstateSet[jjnewStateCnt++] = 33;
                  break;
               case 45:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 44;
                  break;
               case 46:
                  if (curChar == 87)
                     jjstateSet[jjnewStateCnt++] = 45;
                  break;
               case 47:
                  if (curChar == 84)
                     jjAddStates(6, 7);
                  break;
               case 50:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjAddStates(69, 70);
                  break;
               case 52:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 47;
                  break;
               case 53:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 52;
                  break;
               case 54:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 53;
                  break;
               case 55:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 54;
                  break;
               case 56:
                  if (curChar == 65)
                     jjstateSet[jjnewStateCnt++] = 55;
                  break;
               case 57:
                  if (curChar == 80)
                     jjstateSet[jjnewStateCnt++] = 56;
                  break;
               case 58:
                  if (curChar == 68)
                     jjAddStates(8, 9);
                  break;
               case 60:
                  if ((0x7fffffeL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 61;
                  break;
               case 61:
                  if ((0x7fffffeL & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 62;
                  break;
               case 67:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 58;
                  break;
               case 68:
                  if (curChar == 74)
                     jjAddStates(62, 64);
                  break;
               case 70:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 69;
                  break;
               case 71:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 70;
                  break;
               case 72:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 71;
                  break;
               case 73:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 72;
                  break;
               case 74:
                  if (curChar == 101 && kind > 16)
                     kind = 16;
                  break;
               case 75:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 74;
                  break;
               case 76:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 75;
                  break;
               case 77:
                  if (curChar == 108)
                     jjCheckNAdd(0);
                  break;
               case 78:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 77;
                  break;
               case 79:
                  if (curChar == 77)
                     jjAddStates(58, 61);
                  break;
               case 80:
                  if (curChar == 82)
                     jjAddStates(10, 11);
                  break;
               case 83:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjAddStates(71, 72);
                  break;
               case 85:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 80;
                  break;
               case 86:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 85;
                  break;
               case 87:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 86;
                  break;
               case 88:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 87;
                  break;
               case 89:
                  if (curChar == 67)
                     jjstateSet[jjnewStateCnt++] = 88;
                  break;
               case 90:
                  if (curChar == 68)
                     jjstateSet[jjnewStateCnt++] = 89;
                  break;
               case 91:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 90;
                  break;
               case 92:
                  if (curChar == 104 && kind > 16)
                     kind = 16;
                  break;
               case 93:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 92;
                  break;
               case 94:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 93;
                  break;
               case 95:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 94;
                  break;
               case 96:
                  if (curChar == 97)
                     jjCheckNAdd(0);
                  break;
               case 97:
                  if (curChar == 69)
                     jjCheckNAdd(34);
                  break;
               case 98:
                  if (curChar == 76)
                     jjCheckNAdd(97);
                  break;
               case 99:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 98;
                  break;
               case 100:
                  if (curChar == 66)
                     jjstateSet[jjnewStateCnt++] = 99;
                  break;
               case 101:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 100;
                  break;
               case 102:
                  if (curChar == 72)
                     jjAddStates(56, 57);
                  break;
               case 103:
                  if (curChar == 83)
                     jjAddStates(12, 17);
                  break;
               case 105:
                  if (curChar == 110)
                     jjCheckNAddTwoStates(106, 110);
                  break;
               case 107:
               case 137:
                  if (curChar == 111)
                     jjCheckNAdd(105);
                  break;
               case 108:
                  if (curChar == 77)
                     jjstateSet[jjnewStateCnt++] = 107;
                  break;
               case 109:
                  if (curChar == 100)
                     jjCheckNAddTwoStates(106, 110);
                  break;
               case 123:
               case 139:
                  if (curChar == 101)
                     jjCheckNAdd(109);
                  break;
               case 124:
                  if (curChar == 87)
                     jjstateSet[jjnewStateCnt++] = 123;
                  break;
               case 125:
                  if (curChar == 105)
                     jjCheckNAddTwoStates(106, 110);
                  break;
               case 126:
               case 141:
                  if (curChar == 114)
                     jjCheckNAdd(125);
                  break;
               case 127:
                  if (curChar == 70)
                     jjstateSet[jjnewStateCnt++] = 126;
                  break;
               case 128:
                  if (curChar == 84)
                     jjAddStates(73, 74);
                  break;
               case 129:
                  if (curChar == 101)
                     jjCheckNAddTwoStates(106, 110);
                  break;
               case 130:
               case 144:
                  if (curChar == 117)
                     jjCheckNAdd(129);
                  break;
               case 131:
                  if (curChar == 117)
                     jjCheckNAddTwoStates(106, 110);
                  break;
               case 132:
               case 145:
                  if (curChar == 104)
                     jjCheckNAdd(131);
                  break;
               case 133:
                  if (curChar == 83)
                     jjAddStates(75, 76);
                  break;
               case 134:
                  if (curChar == 116)
                     jjCheckNAddTwoStates(106, 110);
                  break;
               case 135:
               case 147:
                  if (curChar == 97)
                     jjCheckNAdd(134);
                  break;
               case 136:
               case 148:
                  if (curChar == 117)
                     jjCheckNAdd(105);
                  break;
               case 138:
                  if (curChar == 77)
                     jjstateSet[jjnewStateCnt++] = 137;
                  break;
               case 140:
                  if (curChar == 87)
                     jjstateSet[jjnewStateCnt++] = 139;
                  break;
               case 142:
                  if (curChar == 70)
                     jjstateSet[jjnewStateCnt++] = 141;
                  break;
               case 143:
                  if (curChar == 84)
                     jjAddStates(77, 78);
                  break;
               case 146:
                  if (curChar == 83)
                     jjAddStates(79, 80);
                  break;
               case 149:
                  if (curChar == 82)
                     jjstateSet[jjnewStateCnt++] = 103;
                  break;
               case 150:
                  if (curChar == 85)
                     jjstateSet[jjnewStateCnt++] = 149;
                  break;
               case 151:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 150;
                  break;
               case 152:
                  if (curChar == 77)
                     jjCheckNAdd(97);
                  break;
               case 153:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 152;
                  break;
               case 156:
                  if (curChar == 68)
                     jjAddStates(53, 55);
                  break;
               case 158:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 157;
                  break;
               case 159:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 158;
                  break;
               case 160:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 159;
                  break;
               case 161:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 160;
                  break;
               case 162:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 161;
                  break;
               case 163:
                  if (curChar == 82)
                     jjAddStates(23, 24);
                  break;
               case 166:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjAddStates(81, 82);
                  break;
               case 169:
                  if (curChar == 68)
                     jjAddStates(83, 84);
                  break;
               case 176:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 169;
                  break;
               case 177:
                  if (curChar == 95)
                     jjstateSet[jjnewStateCnt++] = 176;
                  break;
               case 178:
                  if (curChar == 71)
                     jjstateSet[jjnewStateCnt++] = 177;
                  break;
               case 179:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 178;
                  break;
               case 180:
                  if (curChar == 82)
                     jjstateSet[jjnewStateCnt++] = 179;
                  break;
               case 181:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 163;
                  break;
               case 182:
                  if (curChar == 84)
                     jjstateSet[jjnewStateCnt++] = 181;
                  break;
               case 183:
                  if (curChar == 67)
                     jjstateSet[jjnewStateCnt++] = 182;
                  break;
               case 184:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 183;
                  break;
               case 185:
                  if (curChar == 66)
                     jjAddStates(25, 26);
                  break;
               case 190:
                  if (curChar == 121)
                     jjCheckNAddTwoStates(191, 192);
                  break;
               case 196:
               case 233:
                  if (curChar == 114)
                     jjCheckNAdd(190);
                  break;
               case 197:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 196;
                  break;
               case 198:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 197;
                  break;
               case 199:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 198;
                  break;
               case 200:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 199;
                  break;
               case 201:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 200;
                  break;
               case 202:
                  if (curChar == 70)
                     jjstateSet[jjnewStateCnt++] = 201;
                  break;
               case 203:
                  if (curChar == 114)
                     jjCheckNAddTwoStates(191, 192);
                  break;
               case 204:
               case 212:
               case 218:
               case 225:
                  if (curChar == 101)
                     jjCheckNAdd(203);
                  break;
               case 205:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 204;
                  break;
               case 206:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 205;
                  break;
               case 207:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 206;
                  break;
               case 208:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 207;
                  break;
               case 209:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 208;
                  break;
               case 210:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 209;
                  break;
               case 211:
                  if (curChar == 83)
                     jjstateSet[jjnewStateCnt++] = 210;
                  break;
               case 213:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 212;
                  break;
               case 214:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 213;
                  break;
               case 215:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 214;
                  break;
               case 216:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 215;
                  break;
               case 217:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 216;
                  break;
               case 219:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 218;
                  break;
               case 220:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 219;
                  break;
               case 221:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 220;
                  break;
               case 222:
                  if (curChar == 118)
                     jjstateSet[jjnewStateCnt++] = 221;
                  break;
               case 223:
                  if (curChar == 111)
                     jjstateSet[jjnewStateCnt++] = 222;
                  break;
               case 224:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 223;
                  break;
               case 226:
                  if (curChar == 98)
                     jjstateSet[jjnewStateCnt++] = 225;
                  break;
               case 227:
                  if (curChar == 109)
                     jjstateSet[jjnewStateCnt++] = 226;
                  break;
               case 228:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 227;
                  break;
               case 229:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 228;
                  break;
               case 230:
                  if (curChar == 101)
                     jjstateSet[jjnewStateCnt++] = 229;
                  break;
               case 231:
                  if (curChar == 68)
                     jjstateSet[jjnewStateCnt++] = 230;
                  break;
               case 232:
                  if (curChar == 74)
                     jjAddStates(85, 87);
                  break;
               case 234:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 233;
                  break;
               case 235:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 234;
                  break;
               case 236:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 235;
                  break;
               case 237:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 236;
                  break;
               case 238:
                  if (curChar == 101)
                     jjCheckNAddTwoStates(191, 192);
                  break;
               case 239:
                  if (curChar == 110)
                     jjstateSet[jjnewStateCnt++] = 238;
                  break;
               case 240:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 239;
                  break;
               case 241:
                  if (curChar == 108)
                     jjCheckNAdd(190);
                  break;
               case 242:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 241;
                  break;
               case 243:
                  if (curChar == 77)
                     jjAddStates(88, 89);
                  break;
               case 244:
                  if (curChar == 104)
                     jjCheckNAddTwoStates(191, 192);
                  break;
               case 245:
                  if (curChar == 99)
                     jjstateSet[jjnewStateCnt++] = 244;
                  break;
               case 246:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 245;
                  break;
               case 247:
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 246;
                  break;
               case 248:
                  if (curChar == 97)
                     jjCheckNAdd(190);
                  break;
               case 249:
                  if (curChar == 65)
                     jjAddStates(90, 91);
                  break;
               case 250:
                  if (curChar == 108)
                     jjCheckNAddTwoStates(191, 192);
                  break;
               case 251:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 250;
                  break;
               case 252:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 251;
                  break;
               case 253:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 252;
                  break;
               case 254:
                  if (curChar == 116)
                     jjCheckNAddTwoStates(191, 192);
                  break;
               case 255:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 254;
                  break;
               case 256:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 255;
                  break;
               case 257:
                  if (curChar == 103)
                     jjstateSet[jjnewStateCnt++] = 256;
                  break;
               case 258:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 257;
                  break;
               case 259:
                  if (curChar == 79)
                     jjstateSet[jjnewStateCnt++] = 185;
                  break;
               case 260:
                  if (curChar == 65)
                     jjAddStates(50, 52);
                  break;
               case 261:
                  if (curChar == 108 && kind > 16)
                     kind = 16;
                  break;
               case 262:
                  if (curChar == 105)
                     jjstateSet[jjnewStateCnt++] = 261;
                  break;
               case 263:
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 262;
                  break;
               case 264:
                  if (curChar == 112)
                     jjstateSet[jjnewStateCnt++] = 263;
                  break;
               case 265:
                  if (curChar == 116 && kind > 16)
                     kind = 16;
                  break;
               case 266:
                  if (curChar == 115)
                     jjstateSet[jjnewStateCnt++] = 265;
                  break;
               case 267:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 266;
                  break;
               case 268:
                  if (curChar == 103)
                     jjstateSet[jjnewStateCnt++] = 267;
                  break;
               case 269:
                  if (curChar == 117)
                     jjstateSet[jjnewStateCnt++] = 268;
                  break;
               case 270:
                  if (curChar == 83)
                     jjAddStates(48, 49);
                  break;
               case 273:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     jjAddStates(92, 93);
                  break;
               case 275:
                  if (curChar == 83)
                     jjstateSet[jjnewStateCnt++] = 270;
                  break;
               case 276:
                  if (curChar == 69)
                     jjstateSet[jjnewStateCnt++] = 275;
                  break;
               case 277:
                  if (curChar == 82)
                     jjstateSet[jjnewStateCnt++] = 276;
                  break;
               case 278:
                  if (curChar == 68)
                     jjstateSet[jjnewStateCnt++] = 277;
                  break;
               case 279:
                  if (curChar == 68)
                     jjstateSet[jjnewStateCnt++] = 278;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 280 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   35, 36, 37, 37, 38, 43, 48, 49, 59, 60, 81, 82, 104, 138, 140, 142, 
   143, 146, 108, 124, 127, 128, 133, 164, 165, 186, 187, 188, 189, 202, 211, 217, 
   224, 231, 232, 243, 249, 189, 202, 211, 217, 224, 231, 232, 243, 249, 191, 192, 
   271, 272, 264, 269, 279, 162, 184, 259, 151, 153, 91, 95, 96, 101, 73, 76, 
   78, 31, 32, 40, 41, 50, 51, 83, 84, 130, 132, 135, 136, 144, 145, 147, 
   148, 166, 167, 170, 171, 237, 240, 242, 247, 248, 253, 258, 273, 274, 
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, "\173", "\175", "\54", null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, 
"\120\110\117\116\105\123", null, null, null, null, null, null, null, null, null, null, null, };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};
static final long[] jjtoToken = {
   0xac62937c1L, 
};
static final long[] jjtoSkip = {
   0x3eL, 
};
protected SimpleCharStream input_stream;
private final int[] jjrounds = new int[280];
private final int[] jjstateSet = new int[560];
protected char curChar;
/** Constructor. */
public MedParserTokenManager(SimpleCharStream stream){
   if (SimpleCharStream.staticFlag)
      throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
   input_stream = stream;
}

/** Constructor. */
public MedParserTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 280; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100003600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

}
